CC = gcc
FLAGS = -Wall
PROGRAM_NAME = main
DIR_PATH = ..

test:
	$(CC) $(PROGRAM_NAME).c -o $(PROGRAM_NAME)
	./$(PROGRAM_NAME) $(DIR_PATH)

test_input:
	$(CC) $(PROGRAM_NAME).c -o $(PROGRAM_NAME)
	./$(PROGRAM_NAME)

clean:
	rm main