CC = gcc
FLAGS = -Wall
PROGRAM_NAME = main
SRC_FILE = ../Files/test.txt
CHAR = a

test:
	$(CC) $(PROGRAM_NAME).c -o $(PROGRAM_NAME)
	./$(PROGRAM_NAME) $(CHAR) $(SRC_FILE)

test_input:
	$(CC) $(PROGRAM_NAME).c -o $(PROGRAM_NAME)
	./$(PROGRAM_NAME)

clean:
	rm main